<?php

namespace xes;
class Paragraphs {
	private $lines = array(
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras fermentum blandit tincidunt. Phasellus vitae dui ac mauris vulputate varius euismod vel ipsum. Integer ultrices elit dolor. Sed ac orci a mi suscipit aliquam. Aenean id egestas neque, ac scelerisque quam. Etiam in mauris non ex pellentesque pulvinar. Mauris eu dui leo. Morbi sit amet dictum est. Curabitur quis sagittis sem. Integer gravida nisl tellus, ut facilisis nulla euismod ut. Vivamus suscipit purus pulvinar, laoreet magna at, pulvinar augue. Proin eget interdum odio. Curabitur viverra metus sit amet metus dignissim vehicula.",
		"Nam vel finibus arcu. Integer lobortis iaculis elementum. Aenean sed lacinia tortor, id iaculis nunc. Nam sagittis lectus in nisl fermentum, sit amet mattis dui blandit. Fusce consequat bibendum ante. Curabitur iaculis tellus sit amet tortor ornare, ut iaculis eros condimentum. Fusce scelerisque viverra auctor.",
		"Mauris pretium nibh nec lorem posuere tincidunt. Integer id auctor enim, id fermentum lectus. Vivamus tortor nibh, tincidunt eget aliquam ac, iaculis at nisi. Suspendisse fringilla ipsum vel lorem venenatis dapibus. Ut id mauris iaculis, rutrum mi nec, accumsan metus. Cras tincidunt pretium interdum. Donec maximus quam eu imperdiet gravida.",
		"Cras augue mauris, consectetur in aliquam quis, facilisis ut nulla. Mauris nisi est, porttitor quis aliquam at, aliquam et odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam suscipit non odio a elementum. Phasellus bibendum dui ac congue commodo. Nam finibus suscipit nulla at gravida. Vivamus sed libero dolor. Mauris vulputate convallis fringilla. Sed ac purus nunc. Quisque nulla diam, scelerisque tincidunt nisi quis, pretium blandit nisi. Sed rhoncus sagittis mauris. Maecenas eget cursus quam. Suspendisse ac ipsum in nulla consequat ultrices. Ut semper, turpis pretium vehicula rutrum, enim quam finibus est, et blandit arcu nulla vel leo. Proin id hendrerit nibh. Nam iaculis ex quis mollis semper.",
		"Duis semper, ipsum sit amet rhoncus ultricies, tellus ligula pharetra nisi, eget laoreet ipsum lorem in est. Etiam convallis finibus aliquam. Suspendisse porta vel nibh in egestas. Integer quis dui id lacus tempor lacinia non in sem. Suspendisse laoreet purus nisl, vel elementum purus dignissim eu. Aliquam quis tempor quam. Suspendisse ultrices maximus quam. Donec id gravida orci. Sed iaculis venenatis quam.",
		"Phasellus sed mi quis purus ullamcorper euismod. Donec bibendum, neque at consectetur interdum, eros orci varius est, et dignissim mi risus eu nulla. Proin non varius lectus. Cras pharetra enim est, et lacinia magna pretium id. Sed quis lectus lectus. Cras finibus quam id luctus fermentum. Phasellus hendrerit sollicitudin lacus in hendrerit. Cras lacus magna, placerat at tellus vitae, rutrum malesuada dui. Nulla vehicula lectus a nisi semper convallis. Fusce porttitor mauris vel leo sollicitudin, sit amet vulputate est tincidunt. Integer porttitor libero velit. Nullam condimentum, lorem sed gravida facilisis, purus diam mollis odio, laoreet efficitur felis eros nec dolor. Vestibulum non metus pharetra, pharetra tortor et, posuere sapien.",
		"Donec a sem erat. Curabitur congue mi id nunc tincidunt pretium. Pellentesque consequat libero risus, ac mollis nibh scelerisque ut. Nullam dignissim sem iaculis sem mollis interdum sollicitudin et sem. Mauris consequat, velit eu pulvinar maximus, velit nunc ultricies libero, vel dapibus sapien risus id elit. Quisque vitae risus sed ante dignissim aliquam sit amet in enim. Nam cursus, lorem congue volutpat auctor, odio quam egestas enim, vitae sollicitudin ligula mauris eget erat. Sed semper vel ante ut semper. Mauris elementum hendrerit tristique. Nunc sollicitudin quam at porta lobortis. Curabitur commodo tortor lorem, vitae ultricies orci sagittis a. Suspendisse gravida velit quis felis dapibus convallis. Phasellus sed hendrerit lorem, nec sollicitudin sapien. Morbi nec nisl non odio pellentesque pulvinar. Suspendisse eu eleifend magna, ut venenatis arcu.",
		"Sed ultricies lectus venenatis lectus lobortis, eget ornare lacus accumsan. Aliquam libero risus, semper eget finibus non, lacinia ac dui. Aenean interdum nulla sollicitudin est viverra interdum. Nulla facilisi. Phasellus bibendum blandit bibendum. Donec finibus, eros ut malesuada vehicula, nibh est aliquam libero, nec auctor elit arcu et odio. Integer euismod hendrerit dolor, in imperdiet risus sollicitudin et. Aliquam vehicula ipsum ante, et pulvinar ipsum pharetra a.",
		"Fusce ex magna, aliquet venenatis varius venenatis, bibendum quis sapien. Pellentesque fringilla sed erat ut hendrerit. Donec vel rutrum sapien. Quisque fermentum non diam eu varius. Vestibulum blandit felis in felis pulvinar pulvinar. Donec urna nunc, venenatis sed ipsum sit amet, sagittis sollicitudin sem. Aliquam odio metus, hendrerit non faucibus in, sollicitudin vitae ante. Pellentesque vel massa congue, lobortis odio et, tincidunt velit. Cras pellentesque leo sed dui hendrerit rutrum. Aliquam at consequat eros, ornare ullamcorper dolor. Maecenas vitae dui massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. In dignissim neque sit amet leo tincidunt, quis suscipit eros finibus.",
		"Aliquam pretium laoreet lacus. Phasellus suscipit a massa non viverra. Duis efficitur vulputate ligula, ac venenatis massa aliquet nec. Sed accumsan congue enim sit amet placerat. Suspendisse potenti. Donec faucibus ipsum sed turpis tempor commodo vel ac quam. Cras eleifend imperdiet nibh, nec sagittis enim tincidunt suscipit. Nullam varius blandit sapien in lacinia. Praesent lectus risus, facilisis in odio non, molestie vestibulum eros. Phasellus pretium, ante non viverra congue, mi turpis ornare arcu, et vehicula lorem quam at tortor.",
		"Nam dapibus urna ex, vel pretium turpis fringilla in. Morbi nisi purus, vehicula ut viverra id, dictum at lorem. Curabitur diam arcu, vestibulum ut viverra ut, consectetur in eros. Donec ac augue fringilla orci porta ultrices. Vivamus quis mattis tortor, nec dapibus metus. Nulla volutpat nisi ac neque feugiat hendrerit. Proin congue orci eget efficitur varius. Etiam id gravida velit. Curabitur non nunc at leo facilisis auctor eu quis lorem. Vivamus id ex vitae ipsum semper imperdiet eget a purus. Fusce pretium velit urna, nec facilisis velit ultrices ac. Nunc vehicula et purus maximus imperdiet. Ut cursus, eros et eleifend pellentesque, neque est varius mauris, at convallis sapien elit sed est. Morbi fermentum nisl ac neque consequat, at malesuada tortor pretium. Nam ex purus, sagittis non vehicula vel, interdum in enim.",
		"Praesent dictum lacus quis velit porttitor elementum. Sed ultrices elit sit amet lorem lacinia, nec sodales diam pellentesque. Suspendisse eget velit eget risus gravida porttitor sed quis erat. Fusce vel sem sit amet dolor aliquam lobortis. Ut et pellentesque metus. In at scelerisque purus. Sed pretium mattis dapibus. Nulla nisi urna, pretium quis tristique in, aliquam luctus elit. Etiam dignissim augue eu lorem venenatis rhoncus. Sed at augue a dui sagittis ornare et ac orci. Nam volutpat auctor augue non elementum. Nullam vel risus ex. Nunc posuere justo non orci congue, non lobortis neque cursus. Suspendisse mi odio, malesuada sit amet vestibulum et, egestas nec risus. Pellentesque ut felis quis purus accumsan mollis.",
		"Nullam rutrum nulla lorem, sed laoreet neque auctor porttitor. Etiam tempor ligula luctus lacinia ultricies. Proin id condimentum turpis. Quisque sed luctus mi. Duis consequat fermentum magna a posuere. Vestibulum vestibulum aliquet sodales. Aliquam dignissim ultricies convallis. Cras finibus pretium ultrices. Nulla commodo pharetra metus, consectetur sollicitudin sem pulvinar eget. Donec vitae vestibulum eros. Vestibulum sit amet justo neque. Duis vitae vestibulum arcu, vitae condimentum dolor.",
		"Morbi eu ipsum vel nunc tristique consectetur. Integer elementum condimentum ex, pharetra aliquet felis tempor sed. Suspendisse eu sem luctus, tristique nulla id, imperdiet est. Nam elementum lectus et ante egestas, sollicitudin ullamcorper augue pulvinar. Sed quam nulla, finibus ut tristique fringilla, iaculis eget dolor. Maecenas tristique lectus sit amet neque feugiat consectetur. Vivamus quis dui at lacus lacinia placerat.",
		"Sed sollicitudin tincidunt quam, id iaculis tortor efficitur finibus. Vestibulum sed lorem elementum, eleifend tellus vel, scelerisque lorem. Aliquam interdum, felis in blandit placerat, nulla justo iaculis tortor, non ultrices nunc justo et ante. Nulla lorem nisl, tincidunt eget aliquet vel, varius in tortor. Sed eleifend, sem quis feugiat aliquam, ipsum felis interdum dolor, nec congue nisi urna ut risus. In eu massa mi. Sed aliquam eu arcu a facilisis. Integer tincidunt volutpat nulla non tempor. Sed non ante maximus magna pulvinar dignissim id at est. Donec tempor felis ac rhoncus faucibus. Mauris non urna id justo fermentum condimentum.",
		"Vivamus quis sem at urna malesuada tempor sit amet nec tellus. Donec et maximus tellus, suscipit gravida nulla. Nunc non arcu dolor. Maecenas viverra ullamcorper lacus, non placerat nibh interdum et. Cras egestas, elit ullamcorper venenatis maximus, velit ante pharetra enim, ac aliquet mi nibh a purus. Quisque varius ante et justo consequat, quis interdum arcu ullamcorper. Mauris dignissim ullamcorper nisl. Donec eleifend laoreet metus at finibus. Nulla quis arcu ac eros ultrices varius nec eget elit. Quisque mollis quam at leo scelerisque ultricies. Nam non tincidunt augue. Ut sit amet lorem vitae nibh laoreet gravida. Praesent sem eros, tincidunt id lacinia quis, faucibus nec erat. Cras malesuada cursus arcu id venenatis.",
		"Etiam sollicitudin ultricies est at iaculis. Maecenas ac pulvinar nisi. Nunc non ex ac neque gravida vestibulum ornare non lacus. Ut ante nunc, sagittis ut diam eget, pulvinar convallis sapien. Donec ex dolor, efficitur non mauris eu, maximus ornare purus. Donec nisl purus, aliquet id velit pellentesque, porta rutrum nisl. Vivamus gravida lacinia nisi sed tristique. Vestibulum ut tristique tortor, quis porttitor mauris. Ut nunc arcu, suscipit vitae odio a, vehicula laoreet dolor. Cras mollis sem a fermentum consectetur.",
		"Donec nisi metus, mollis sit amet egestas vel, pharetra at turpis. Pellentesque in est sed purus tincidunt bibendum. In imperdiet ante et luctus luctus. Ut ac feugiat est. Sed tristique porttitor dolor, et tristique nibh vestibulum vel. Aliquam consequat sollicitudin quam sollicitudin sollicitudin. Nam dictum nec dui a efficitur. Suspendisse sit amet efficitur mauris, ac iaculis nulla. Sed risus sapien, porttitor sed justo at, pellentesque fringilla turpis.",
		"Sed non fermentum quam. Integer vulputate felis euismod, consequat est non, iaculis nulla. Suspendisse lectus nisi, consequat non aliquam quis, porttitor eu orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus ornare non libero vel tempor. Aenean non odio rhoncus tellus elementum volutpat. Pellentesque suscipit nunc tellus, non suscipit lectus rhoncus a. Mauris euismod volutpat venenatis.",
		"Sed vitae pretium justo. Curabitur vehicula ultrices orci, at finibus ipsum euismod a. Aliquam ut massa vitae lorem condimentum rutrum at eu enim. Pellentesque porttitor, dui nec iaculis interdum, nisi sem scelerisque dolor, scelerisque vestibulum tellus ipsum vitae dolor. Vestibulum nec rhoncus eros. Nam luctus ipsum eget nibh tincidunt efficitur. Suspendisse interdum purus vel erat consequat, sed pretium nunc rutrum. Integer nibh erat, fermentum id commodo egestas, rhoncus ut tortor. Aenean facilisis porttitor dolor ac mattis. Sed vitae ultrices diam, ac dictum ligula. Suspendisse at nibh vitae tortor faucibus imperdiet vitae eget arcu. Phasellus a ante felis. Pellentesque efficitur nisl nec risus dictum, in euismod nisi venenatis."
);

	public function getLines($paragraphs = 1) {

		$mod = count($this->lines);
		
		$lines = $this->lines;
		shuffle($lines);

		$result = array();
		for ($i = 0; $i < $paragraphs; $i++) {
			$result[] = $lines[$i % $mod];
		}
		
		
		return '<p>'.implode("</p><p>", $result).'</p>';
	}
}

?>
