<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'xes\\' => array($vendorDir . '/xes/templater/src', $vendorDir . '/xes/cacher/src'),
);
